#ifndef CONSTANTS_HPP
#define CONSTANTS_HPP

constexpr int MAXIMUM_WINDOW_WIDTH = 1920;
constexpr int MAXIMUM_WINDOW_HEIGHT = 1080;
constexpr int MINIMUM_WINDOW_WIDTH = 320;
constexpr int MINIMUM_WINDOW_HEIGHT = 240;
constexpr int INITIAL_WINDOW_WIDTH = 1920;
constexpr int INITIAL_WINDOW_HEIGHT = 1080;

#endif // CONSTANTS_HPP